name: CI

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "--deny warnings"
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: cargo test --verbose --features rusb

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check code formatting
      run: cargo fmt -- --check
    - name: Run Clippy rusb
      run: cargo clippy --features rusb
    - name: Run Clippy nusb
      run: cargo clippy --features nusb
